**NEWTON'S ALGORITHM**

<center><img src = "https://i.imgur.com/oMGO0Ru.png" align = "center"> </center>


**Example 1**

Please solve the following problem using Newton Method

\begin{align}
4x_1^2 - 20x_1 + \frac{1}{4}x_2^2 + 8 =0\\
\frac{1}{2}x_1x_2^2 + 2x_1 - 5x_2 + 8 =0
\end{align}

use $\mathbf{x}^0 =(0,0)^t$


First define function F(X)

In [108]:
import numpy as np

def F(X):
  f1 =  4*X[0]**2 - 20*X[0] + (1/4)*X[1]**2 + 8
  f2 = (1/2)*X[0]*X[1]**2 + 2*X[0] - 5*X[1] + 8  
  return [f1, f2]

x = [0, 0]
example = F(x)
example

[8.0, 8.0]

Define Jacobian Matrix

In [109]:
def J(X):
   a11 = 8*X[0] - 20
   a12 = (1/2)*X[1]
   a21 = (1/2)*X[1]**2 + 2
   a22 = X[0]*X[1] - 5

   return [[a11, a12],[a21, a22]]

exp = J(x)
exp  



[[-20, 0.0], [2.0, -5]]

Define the error $||\mathbf{x}^{(k)} - \mathbf{x}^{(k-1)}||_{\infty}= \displaystyle \min_k \{|\mathbf{x}^{(k)} - \mathbf{x}^{(k-1)}| \} < \epsilon$

---



In [110]:
def error(X, X1):
  return  min(np.absolute(X-X1))

Define input problem $\mathbf{x}^0$, $TOL$ and $N$ iteration

In [111]:
x = [0., 0.]
TOL = 0.00001
N = 200

Program the algorithm such that the results is given as the following table

In [112]:
#step 1
k= 1
xold=np.ones(len(x))

print('iteration: ', k)
print('error: ',error(x,xold))
print(x)

#Step 2 
while (k<=N) and (error(x,xold)>TOL): 
  #step 3
  Fx = F(x)
  Jac = J(x)
  #step 4
  y = np.linalg.inv(Jac)@(Fx)
  xold = x
  #step 5
  x = x-y
  #step 6
  k = k +1
  print('iteration: ', k)
  print('error: ',error(x,xold)) 
  print(x)



iteration:  1
error:  1.0
[0.0, 0.0]
iteration:  2
error:  0.4
[0.4  1.76]
iteration:  3
error:  0.09589361055293155
[0.49589361 1.98342347]
iteration:  4
error:  0.004094003971733762
[0.49998761 1.99993705]
iteration:  5
error:  1.238532588371255e-05
[0.5 2. ]
iteration:  6
error:  1.4945089610307605e-10
[0.5 2. ]


**Example 2**

<center><img src = "https://i.imgur.com/XXNqRaD.png" align = "center"> </center>

First define function F(X)

In [113]:
import numpy as np
import pandas as pd
import sys

epsilon = sys.float_info.epsilon

def F(X):
  f1 = 3*X[0] - np.cos(X[1]*X[2]) - (1/2)
  f2 = X[0]**2 - 81*(X[1] + 0.1)**2 + np.sin(X[2]) + 1.06
  f3 = (epsilon**(-X[0]*X[1])) + 20*X[2] + ((10*np.pi - 3)/3)
  return[f1,f2,f3]


Define Jacobian Matrix

In [114]:
def J(X):
  a11 = 3 
  a12 = 2*X[0]
  a13 = -X[1]*(epsilon**(-X[0]*X[1]))
  a21 = np.sin(X[1]*X[2])
  a22 = -162*X[1] - 16.2
  a23 = -X[0]*(epsilon**(-X[0]*X[1])) 
  a31 = np.sin(X[1]*X[2])
  a32 = np.cos(X[2]) 
  a33 = 20
  return [[a11, a12, a13],[a21, a22, a23], [a31, a32, a33]]

Define the error $||\mathbf{x}^{(k)} - \mathbf{x}^{(k-1)}||_{\infty}= \displaystyle \min_k \{|\mathbf{x}^{(k)} - \mathbf{x}^{(k-*1*)}| \} < \epsilon$

In [115]:
def error(X, X1):
  return min(np.absolute(X-X1))

Define input problem $\mathbf{x}^0$, $TOL$ and $N$ iteration

In [116]:
x = [0.1, 0.1, -0.1]
TOL = 0.0001
N = 200

Program the algorithm such that the results is given as the following table

<center><img src = "https://i.imgur.com/QRvdWEO.png" align = "center"> </center>

In [117]:
#step 1
data = []
k = 1
xold=np.ones(len(x))

print('iteration: ', k)
print('error: ',error(x,xold))
print(x)
data.append(x)
#Step 2 
while (k<=N) and (error(x,xold)>TOL):
  #step 3
  Fx = F(x)
  Jac = J(x)
  #step 4
  y = np.linalg.inv(Jac)@(Fx)
  xold = x
  #step 5
  x = x-y
  #step 6
  k = k+1
  print('iteration: ', k)
  print('error: ',error(x,xold)) 
  print(x)
  data.append(x)

print(pd.DataFrame(data, columns=['x1','x2','x3']))

iteration:  1
error:  0.9
[0.1, 0.1, -0.1]
iteration:  2
error:  0.0682200053236177
[ 0.48341821  0.03177999 -0.54171087]
iteration:  3
error:  0.017620813074316954
[ 0.50889751  0.00301095 -0.55933169]
iteration:  4
error:  0.005330505461286043
[ 0.50184311 -0.00231956 -0.52621256]
iteration:  5
error:  0.0021815476493319734
[ 4.99266497e-01 -1.38007690e-04 -5.21638503e-01]
iteration:  6
error:  0.0002546646003129362
[ 4.99915320e-01  1.16656910e-04 -5.23485797e-01]
iteration:  7
error:  0.00010918380759869746
[ 5.00036379e-01  7.47310241e-06 -5.23699258e-01]
iteration:  8
error:  1.3510236147527085e-05
[ 5.00004504e-01 -6.03713373e-06 -5.23604926e-01]
         x1        x2        x3
0  0.100000  0.100000 -0.100000
1  0.483418  0.031780 -0.541711
2  0.508898  0.003011 -0.559332
3  0.501843 -0.002320 -0.526213
4  0.499266 -0.000138 -0.521639
5  0.499915  0.000117 -0.523486
6  0.500036  0.000007 -0.523699
7  0.500005 -0.000006 -0.523605


# Exercise

<center><img src = "https://i.imgur.com/a7Lkz1K.png" align = "center"> </center>
